fixes

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -109,23 +109,34 @@ jobs:
         id: supports_usns
         run: |
           if [ "${{ steps.get_os.outputs.os }}" == "ubi" ]; then
-            echo "supports_usns=false"
+            echo "supports_usns=false" >> "$GITHUB_OUTPUT"
           else
             echo "supports_usns=true" >> "$GITHUB_OUTPUT"
           fi
-        
+
   poll_usns:
     name: Poll USNs
     runs-on: ubuntu-22.04
     needs: preparation
-    if: ${{ needs.preparation.outputs.supports_usns == 'true' }}
     strategy:
       matrix:
         stacks: ${{ fromJSON(needs.preparation.outputs.stacks) }}
     outputs:
       usns: ${{ steps.convert_usn_array.outputs.usns }}
+      skip: ${{ steps.skip_poll_usns.outputs.skip }}
     steps:
+    - name: Check if Poll USNs should be skipped
+      id: skip_poll_usns
+      run: |
+        if [ "${{ needs.preparation.outputs.supports_usns }}" == "true" ]; then
+          echo "skip=false" >> "$GITHUB_OUTPUT"
+        else
+          echo "skip=true" >> "$GITHUB_OUTPUT"
+          echo "usns=false" >> "$GITHUB_OUTPUT"
+        fi
+
     - name: Find and Download Previous Build Receipt
+      if: ${{ steps.skip_poll_usns.outputs.skip == 'false' }}
       id: previous_build
       uses: paketo-buildpacks/github-config/actions/release/find-and-download-asset@main
       with:
@@ -137,6 +148,7 @@ jobs:
         strict: true
 
     - name: Find and Download Previous Run Receipt
+      if: ${{ steps.skip_poll_usns.outputs.skip == 'false' }}
       id: previous_run
       uses: paketo-buildpacks/github-config/actions/release/find-and-download-asset@main
       with:
@@ -153,13 +165,18 @@ jobs:
 
     - name: Get Package List
       id: packages
-      if: ${{ steps.previous_build.outputs.output_path != '' && steps.previous_run.outputs.output_path != '' }}
+      if: >- 
+        ${{
+          steps.skip_poll_usns.outputs.skip == 'false' &&
+          steps.previous_build.outputs.output_path != '' && steps.previous_run.outputs.output_path != '' 
+        }}
       uses: paketo-buildpacks/github-config/actions/stack/generate-package-list@main
       with:
         build_receipt: "${{ github.workspace }}/${{ matrix.stacks.build_image }}-${{ env.RECEIPT_FILENAME_SUFFIX }}"
         run_receipt: "${{ github.workspace }}/${{ matrix.stacks.run_image }}-${{ env.RECEIPT_FILENAME_SUFFIX }}"
 
     - name: Find and Download Previous Patched USNs
+      if: ${{ steps.skip_poll_usns.outputs.skip == 'false' }}
       id: download_patched
       uses: paketo-buildpacks/github-config/actions/release/find-and-download-asset@main
       with:
@@ -172,12 +189,13 @@ jobs:
     # TODO test with USNs
     - name: Output Patched USNs as JSON String
       id: patched
-      if: ${{ steps.download_patched.outputs.output_path != '' }}
+      if: ${{ steps.skip_poll_usns.outputs.skip == 'false' && steps.download_patched.outputs.output_path != '' }}
       run: |
         patched=$(jq --compact-output . < "${GITHUB_WORKSPACE}/${{ matrix.stacks.patched_usns_filename_suffix }}")
         printf "patched=%s\n" "${patched}" >> "$GITHUB_OUTPUT"
 
     - name: Get Stack Distribution Name
+      if: ${{ steps.skip_poll_usns.outputs.skip == 'false' }}
       id: distro
       run: |
         # Extract distro from repo name:
@@ -187,6 +205,7 @@ jobs:
         printf "distro=%s\n" "${distro}" >> "$GITHUB_OUTPUT"
 
     - name: Get New USNs
+      if: ${{ steps.skip_poll_usns.outputs.skip == 'false' }}
       id: usns
       uses: paketo-buildpacks/github-config/actions/stack/get-usns@main
       with:
@@ -199,7 +218,17 @@ jobs:
         # We have to create a directory to store the new usns,
         # otherwise we get a permission denied error
         mkdir -p new-usns
-        echo '${{ steps.usns.outputs.usns }}' > new-usns/${{ matrix.stacks.patched_usns_filename_suffix }}
+
+        if [ "${{ steps.skip_poll_usns.outputs.skip }}" == "true" ]; then
+          echo '[]' > new-usns/${{ matrix.stacks.patched_usns_filename_suffix }}
+        else
+          echo '${{ steps.usns.outputs.usns }}' > new-usns/${{ matrix.stacks.patched_usns_filename_suffix }}
+        fi
+
+
+    # TODO remove before PR
+    - name: Treeeee
+      run: tree .
 
     - name: Upload new USNs 
       uses: actions/upload-artifact@v4
@@ -208,6 +237,7 @@ jobs:
         path: new-usns/${{ matrix.stacks.patched_usns_filename_suffix }}
 
     - name: Convert usn array to boolean
+      if: ${{ steps.skip_poll_usns.outputs.skip == 'false' }}
       id: convert_usn_array
       run: |
         # We convert the array to a boolean as the usns are stored on a file 
@@ -219,12 +249,12 @@ jobs:
   stack_files_changed:
     name: Determine If Stack Files Changed
     runs-on: ubuntu-22.04
-    needs: [ poll_usns, preparation ] 
+    needs: poll_usns 
     if: >- 
       ${{
-        ( ! ( needs.poll_usns.outputs.usns == 'true' && github.event_name == 'schedule' ) && needs.preparation.outputs.supports_usns == 'true' )
+        ( ! ( needs.poll_usns.outputs.usns == 'true' && github.event_name == 'schedule' ) )
         ||
-        ( ! ( github.event_name == 'schedule' ) && needs.preparation.outputs.supports_usns == 'false') 
+        ( ! ( github.event_name == 'schedule' ) && needs.poll_usns.outputs.skip == 'true' ) 
       }}
     outputs:
       stack_files_changed: ${{ steps.compare.outputs.stack_files_changed }}
@@ -258,12 +288,12 @@ jobs:
 
   create_stack:
     name: Create Stack
-    needs: [poll_usns, preparation]
+    needs: [ poll_usns, preparation ] 
     if: >- 
       ${{
-        ( ! ( needs.poll_usns.outputs.usns == 'true' && github.event_name == 'schedule' ) && needs.preparation.outputs.supports_usns == 'true' )
+        ( ! ( needs.poll_usns.outputs.usns == 'true' && github.event_name == 'schedule' ) )
         ||
-        ( ! ( github.event_name == 'schedule' ) && needs.preparation.outputs.supports_usns == 'false') 
+        ( ! ( github.event_name == 'schedule' ) && needs.poll_usns.outputs.skip == 'true' ) 
       }}
     strategy:
       matrix:
@@ -273,17 +303,25 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v4
 
+    # TODO remove before PR
+    - name: Tree
+      run: tree .
+
     - name: Create ${{ matrix.stacks.name }}
       id: create-stack
       run: |
         scripts/create.sh --stack-dir ${{ matrix.stacks.config_dir }} \
                           --build-dir ${{ matrix.stacks.output_dir }}
 
+    # TODO remove before PR
+    - name: Tree
+      run: tree .
+
     - name: Generate Package Receipts
       id: receipts
       run: |
-        scripts/receipts.sh --build-image "${{ matrix.stacks.output_dir }}" \
-                            --run-image "${{ matrix.stacks.output_dir }}" \
+        scripts/receipts.sh --build-image "${{ matrix.stacks.output_dir }}/build.oci" \
+                            --run-image "${{ matrix.stacks.output_dir }}/run.oci" \
                             --build-receipt current-build-receipt-${{ matrix.stacks.name }} \
                             --run-receipt current-run-receipt-${{ matrix.stacks.name }}
         echo "build_receipt=current-build-receipt-${{ matrix.stacks.name }}" >> "$GITHUB_OUTPUT"
@@ -360,6 +398,10 @@ jobs:
         echo '{"components":[]}' > "${{ github.workspace }}/previous-build-receipt-${{ matrix.stacks.name }}"
         echo '{"components":[]}' > "${{ github.workspace }}/previous-run-receipt-${{ matrix.stacks.name }}"
 
+    # TODO remove before PR
+    - name: Treee
+      run: tree .
+
     - name: Find and Download Previous Build Receipt
       if: ${{ steps.check_previous.outputs.exists == 'true' }}
       uses: paketo-buildpacks/github-config/actions/release/find-and-download-asset@main
@@ -400,7 +442,6 @@ jobs:
         previous: "/github/workspace/previous-run-receipt-${{ matrix.stacks.name }}"
         current: "/github/workspace/current-run-receipt-${{ matrix.stacks.name }}"
 
-    # TODO test below step
     - name: Fail If Packages Removed
       id: removed_with_force
       env:
@@ -413,17 +454,15 @@ jobs:
          run=$(jq '. | length' <<< "${RUN_REMOVED}")
          echo "Run packages removed: ${run}"
 
-        # # TODO uncomented for testing purposes
-        #  ## TODO validate with tests that this will work
-        #  # only fail if packages are removed AND the release has not been forced
-        #  if [ "${build}" -gt 0 ] || [ "${run}" -gt 0 ]; then
-        #    if [ "${{ github.event.inputs.force }}" != 'true' ]; then
-        #      echo "Packages removed without authorization. Stack cannot be released."
-        #      exit 1
-        #    else
-        #      echo "packages_removed=true" >> "$GITHUB_OUTPUT"
-        #    fi
-        #  fi
+         # only fail if packages are removed AND the release has not been forced
+         if [ "${build}" -gt 0 ] || [ "${run}" -gt 0 ]; then
+           if [ "${{ github.event.inputs.force }}" != 'true' ]; then
+             echo "Packages removed without authorization. Stack cannot be released."
+             exit 1
+           else
+             echo "packages_removed=true" >> "$GITHUB_OUTPUT"
+           fi
+         fi
 
     # TODO check if there is a more nice way for below code to handle the env variables
     - name: Create/Upload variable artifacts
@@ -555,8 +594,6 @@ jobs:
     - name: Run Acceptance Tests
       run: ./scripts/test.sh
 
-# TODO the pacostas/build-jammy-base: is missing the tag.
-
   force_release_creation:
     name: Force Release Creation
     runs-on: ubuntu-22.04
@@ -566,28 +603,10 @@ jobs:
       run: |
         echo "Force release creation input set to true"
 
-  prepare_release:
-    name: Prepare Release
-    runs-on: ubuntu-22.04
-    needs: [poll_usns, create_stack, diff, run_if_stack_files_changed, run_if_packages_changed, run_if_packages_removed_with_force, test, force_release_creation ]
-    if: ${{ always() && needs.diff.result == 'success' && needs.test.result == 'success' && (needs.run_if_packages_changed.result == 'success' || needs.run_if_stack_files_changed.result == 'success' || needs.force_release_creation.result == 'success' ) }}
-    steps:
-    - name: Checkout With History
-      uses: actions/checkout@v4
-      with:
-        fetch-depth: 0  # gets full history
-
-    - name: Increment Tag
-      if: github.event.inputs.version == ''
-      id: semver
-      uses: paketo-buildpacks/github-config/actions/tag/increment-tag@main
-      with:
-        allow_head_tagged: true
-
   release:
     name: Release
     runs-on: ubuntu-22.04
-    needs: [poll_usns, create_stack, diff, run_if_stack_files_changed, run_if_packages_changed, run_if_packages_removed_with_force, test, force_release_creation, prepare_release, preparation ]
+    needs: [poll_usns, create_stack, diff, run_if_stack_files_changed, run_if_packages_changed, run_if_packages_removed_with_force, test, force_release_creation, preparation ]
     if: |
       ${{ always() &&
       needs.diff.result == 'success' &&
@@ -595,11 +614,12 @@ jobs:
         (needs.run_if_packages_changed.result == 'success' ||
          needs.run_if_stack_files_changed.result == 'success' ||
          needs.force_release_creation.result == 'success' )
-      && needs.prepare_release.result == 'success' 
       }}
     strategy:
       matrix:
         stacks: ${{ fromJSON(needs.preparation.outputs.stacks) }}
+    outputs:
+      tag: ${{ steps.tag.outputs.tag }}
     steps:
     - name: Print Release Reasoning
       run: |
@@ -627,6 +647,24 @@ jobs:
         echo "usns=$usns" >> "$GITHUB_OUTPUT"
         rm ${{ matrix.stacks.patched_usns_filename_suffix }}
 
+    # TODO this might has to be moved on preparation step as it might run
+    # multiple parallel times and it might has to run only once.
+    - name: Increment Tag
+      if: github.event.inputs.version == ''
+      id: semver
+      uses: paketo-buildpacks/github-config/actions/tag/increment-tag@main
+      with:
+        allow_head_tagged: true
+
+    - name: Set Release Tag
+      id: tag
+      run: |
+        tag="${{ github.event.inputs.version }}"
+        if [ -z "${tag}" ]; then
+          tag="${{ steps.semver.outputs.tag }}"
+        fi
+        echo "tag=${tag}" >> "$GITHUB_OUTPUT"
+        
     - name: Write USNs File
       id: write_usns
       if: ${{ steps.poll_usns.outputs.usns != '[]'  }}
@@ -663,15 +701,6 @@ jobs:
         run_packages_modified: ${{ needs.diff.outputs.run_modified }}
         run_packages_removed_with_force: ${{ needs.diff.outputs.run_removed_with_force }}
         patched_usns: ${{ steps.poll_usns.outputs.usns }}
-
-    - name: Set Release Tag
-      id: tag
-      run: |
-        tag="${{ github.event.inputs.version }}"
-        if [ -z "${tag}" ]; then
-          tag="${{ steps.semver.outputs.tag }}"
-        fi
-        echo "tag=${tag}" >> "$GITHUB_OUTPUT"
 
     - name: Setup Release Assets
       id: assets
@@ -819,23 +848,14 @@ jobs:
     - name: Treee
       run: tree .
 
-    - name: Set Release Tag
-      id: tag
-      run: |
-        tag="${{ github.event.inputs.version }}"
-        if [ -z "${tag}" ]; then
-          tag="${{ steps.semver.outputs.tag }}"
-        fi
-        echo "tag=${tag}" >> "$GITHUB_OUTPUT"
-
     - name: Create Release
       uses: paketo-buildpacks/github-config/actions/release/create@main
       with:
         repo: ${{ github.repository }}
         token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
-        tag_name: v${{ steps.tag.outputs.tag }}
+        tag_name: v${{ needs.release.outputs.tag }}
         target_commitish: ${{ github.sha }}
-        name: v${{ steps.tag.outputs.tag }}
+        name: v${{ needs.release.outputs.tag }}
         body: ${{ fromJson(steps.merge_release_bodies.outputs.release_body).text }}
         draft: false
         assets: ${{ steps.merge_release_assets.outputs.assets }}
@@ -844,7 +864,7 @@ jobs:
   failure:
     name: Alert on Failure
     runs-on: ubuntu-22.04
-    needs: [poll_usns, create_stack, diff, test, prepare_release, release, create_release, packages_changed, stack_files_changed]
+    needs: [poll_usns, create_stack, diff, test, release, create_release, packages_changed, stack_files_changed]
     if: ${{ always() && needs.poll_usns.result == 'failure' || needs.create_stack.result == 'failure' || needs.diff.result == 'failure' || needs.test.result == 'failure' || needs.release.result == 'failure' || needs.packages_changed.result == 'failure' || needs.stack_files_changed.result == 'failure' }}
     steps:
     - name: File Failure Alert Issue
